Repository telepace/nexus, pull requests merged in 2025-06, with the labels that each got.

#156 Feature/UI 0602
  frontend/__tests__/components/layout/AppSidebar.test.tsx
  frontend/__tests__/components/layout/MainLayout.test.tsx
  frontend/__tests__/components/layout/Sidebar.test.tsx
  frontend/__tests__/components/layout/TopNavigation.test.tsx
  frontend/app/content-library/page.tsx
  frontend/app/globals.css
  frontend/app/password-recovery/confirm/page.tsx
  frontend/app/prompts/_components/PromptForm.tsx
  frontend/app/prompts/page.tsx
  frontend/app/setup/page.tsx
  frontend/components/actions/google-auth-action.ts
  frontend/components/actions/items-action.ts
  frontend/components/actions/login-action.ts
  frontend/components/layout/AppSidebar.tsx
  frontend/components/layout/MainLayout.tsx
  frontend/components/layout/Sidebar.tsx
  frontend/components/layout/TopNavigation.tsx
  frontend/components/setup/SetupContent.tsx
  frontend/components/ui/button.tsx
  frontend/components/ui/input.tsx
  frontend/components/ui/separator.tsx
  frontend/components/ui/sheet.tsx
  frontend/components/ui/sidebar.tsx
  frontend/components/ui/skeleton.tsx
  frontend/components/ui/tooltip.tsx
  frontend/hooks/use-mobile.ts
  frontend/hooks/useAuthRedirect.ts
  frontend/middleware.ts
  frontend/openapi.json
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 4, Tests, Review effort 3/5

#163 Feature/UI 0604
  backend/app/core/config.py
  frontend/__tests__/app/content-library/reader/[id]/page.test.tsx
  frontend/__tests__/components/ui/prompt-command-dialog.test.tsx
  frontend/app/content-library/page.tsx
  frontend/app/content-library/reader/[id]/ReaderContent.tsx
  frontend/app/content-library/reader/[id]/page.tsx
  frontend/app/globals.css
  frontend/app/test-ai-analysis/page.tsx
  frontend/app/test-css-variables/page.tsx
  frontend/components/layout/AppSidebar.tsx
  frontend/components/layout/MainLayout.tsx
  frontend/components/layout/ReaderLayout.tsx
  frontend/components/ui/VirtualScrollRenderer.tsx
  frontend/components/ui/llm-analysis-card.tsx
  frontend/components/ui/llm-analysis-sidebar.tsx
  frontend/components/ui/prompt-command-dialog.tsx
  frontend/components/ui/prompt-recommendations.tsx
  frontend/lib/stores/llm-analysis-store.ts
  frontend/openapi.json
  website/src/app/[lang]/styles/index.css
Labels: Review effort 3/5

#166 Delete .cursor/website.mdc
  .cursor/website.mdc
Labels: Review effort 1/5

#207 feat: fix neo ui branch
  admin/package.json
  frontend/__tests__/app/content-library/page.test.tsx
  frontend/app/content-library/components/AIAnalysisCard.tsx
  frontend/app/content-library/components/ContentCard.tsx
  frontend/app/content-library/components/ContentList.tsx
  frontend/app/content-library/components/ContentPreview.tsx
  frontend/app/content-library/components/LibraryHeader.tsx
  frontend/app/content-library/hooks/useContentItems.ts
  frontend/app/content-library/page.tsx
  frontend/app/content-library/reader/[id]/ClientContent.tsx
  frontend/app/content-library/types.ts
  frontend/app/content-library/utils/ripple.ts
  frontend/app/globals.css
  frontend/app/providers.tsx
  frontend/components/ai/ContentAnalysisSidebar.tsx
  frontend/components/layout/AppSidebar.tsx
  frontend/components/layout/MainLayout.tsx
  frontend/components/layout/ReaderLayout.tsx
  frontend/components/ui/ProcessingStatusBadge.tsx
  frontend/components/ui/VirtualScrollRenderer.tsx
  frontend/components/ui/enhanced-llm-analysis-sidebar.tsx
  frontend/components/ui/llm-analysis-card.tsx
  frontend/components/ui/prompt-recommendations.tsx
  frontend/lib/stores/useGlobalNotificationStore.ts
Labels: Review effort 4/5

#195 UI/0617 UI更新1（还会有后续更新2）
  admin/package.json
  frontend/__tests__/app/content-library/page.test.tsx
  frontend/app/content-library/components/AIAnalysisCard.tsx
  frontend/app/content-library/components/ContentCard.tsx
  frontend/app/content-library/components/ContentList.tsx
  frontend/app/content-library/components/ContentPreview.tsx
  frontend/app/content-library/components/LibraryHeader.tsx
  frontend/app/content-library/hooks/useContentItems.ts
  frontend/app/content-library/page.tsx
  frontend/app/content-library/reader/[id]/ClientContent.tsx
  frontend/app/content-library/types.ts
  frontend/app/content-library/utils/ripple.ts
  frontend/app/globals.css
  frontend/app/providers.tsx
  frontend/components/ai/ContentAnalysisSidebar.tsx
  frontend/components/layout/AppSidebar.tsx
  frontend/components/layout/MainLayout.tsx
  frontend/components/layout/ReaderLayout.tsx
  frontend/components/ui/ProcessingStatusBadge.tsx
  frontend/components/ui/VirtualScrollRenderer.tsx
  frontend/components/ui/enhanced-llm-analysis-sidebar.tsx
  frontend/components/ui/llm-analysis-card.tsx
  frontend/components/ui/prompt-recommendations.tsx
  frontend/lib/stores/useGlobalNotificationStore.ts
Labels: Review effort 4/5

#220 UI/0626
  frontend/app/content-library/components/ContentCard.tsx
  frontend/app/content-library/components/ContentPreview.tsx
  frontend/app/content-library/page.tsx
  frontend/app/content-library/reader/[id]/ClientContent.tsx
  frontend/app/content-library/reader/[id]/loading.tsx
  frontend/app/globals.css
  frontend/app/test-markdown/page.tsx
  frontend/components/ai/AnalysisCards.tsx
  frontend/components/ai/ContentAnalysisSidebar.tsx
  frontend/components/layout/ReaderLayout.tsx
  frontend/components/ui/MarkdownRenderer.tsx
  frontend/components/ui/VirtualScrollRenderer.tsx
  frontend/components/ui/enhanced-llm-analysis-sidebar.tsx
  frontend/components/ui/icons/CloudIcon.tsx
  frontend/components/ui/llm-analysis-sidebar.tsx
  frontend/components/ui/tooltip.tsx
  frontend/next.config.mjs
Labels: Review effort 4/5

#232 Revert "feat: Enhance content processing and tagging system"
  .env.example
  backend/app/core/config.py
  backend/app/core/redis_client.py
  backend/app/prompt_templates/labels.j2
  backend/app/prompt_templates/preset_tags.json
  backend/app/services/ai/chat_service.py
  backend/app/services/ai_tag_processor.py
  backend/app/services/preprocessing_pipeline.py
  backend/app/tests/core/test_config.py
  backend/app/utils/cache.py
  backend/app/utils/tag_manager.py
  backend/scripts/manage_tags.py
  docker-compose.yml
  frontend/app/content-library/components/ContentCard.tsx
  frontend/app/content-library/components/ContentList.tsx
  frontend/app/content-library/components/DeleteConfirmDialog.tsx
  frontend/app/content-library/hooks/useContentItems.ts
  frontend/app/content-library/page.tsx
  frontend/app/settings/page.tsx
Labels: Review effort 4/5

#235 Prompt/0627
  backend/app/prompt_templates/key_points.j2
  backend/app/prompt_templates/summary.j2
  frontend/__tests__/app/dashboard/page-integration.test.tsx
  frontend/__tests__/components/layout/AddContentModal.test.tsx
  frontend/app/content-library/components/ContentCard.tsx
  frontend/app/content-library/components/ContentList.tsx
  frontend/app/content-library/components/DeleteConfirmDialog.tsx
  frontend/app/content-library/hooks/useContentItems.ts
  frontend/app/content-library/page.tsx
  frontend/app/globals.css
  frontend/app/login/page.tsx
  frontend/app/settings/page.tsx
  frontend/components/ai/ContentAnalysisSidebar.tsx
  frontend/components/ai/ConversationHistory.tsx
  frontend/components/layout/AddContentModal.tsx
  frontend/components/layout/AppSidebar.tsx
  frontend/components/layout/MainLayout.tsx
  frontend/components/layout/ReaderLayout.tsx
  frontend/components/ui/ai-analysis-card.tsx
  frontend/components/ui/button.tsx
  frontend/components/ui/enhanced-llm-analysis-card.tsx
  frontend/components/ui/llm-analysis-card.tsx
  frontend/components/ui/prompt-command-dialog.tsx
  frontend/components/ui/streaming-text.tsx
Labels: Review effort 4/5

#237 feat: Add deep research functionality and update dependencies
  .env.example
  backend/app/alembic/versions/713b69d73b30_add_deep_research_job_table.py
  backend/app/api/main.py
  backend/app/api/routes/deep_research.py
  backend/app/models/__init__.py
  backend/app/models/content.py
  backend/app/schemas/__init__.py
  backend/app/schemas/deep_research.py
  backend/app/services/deep_research_service.py
  backend/app/services/preprocessing_pipeline.py
  backend/app/tests/api/test_deep_research.py
  backend/app/tests/conftest.py
  backend/app/utils/pydantic_compatibility.py
  backend/pyproject.toml
  backend/scripts/create_test_deep_research.py
  backend/scripts/test_deep_research_fix.py
  backend/uv.lock
  frontend/__tests__/app/content-library/page.test.tsx
  frontend/__tests__/app/dashboard/page-integration.test.tsx
  frontend/__tests__/components/ui/prompt-command-dialog.test.tsx
  frontend/__tests__/registerPage.test.tsx
  frontend/__tests__/settings.test.tsx
  frontend/app/layout.tsx
  frontend/app/share/[token]/page.test.tsx
  frontend/components/layout/AddContentModal.tsx
  frontend/components/layout/EnhancedAddContentDialog.tsx
  frontend/components/layout/OptimizedAddContentDialog.tsx
  frontend/components/share/ShareContentModal.test.tsx
  frontend/jest.config.ts
  frontend/public/img/favicon.svg
  litellm/config.yaml
Labels: enhancement, Review effort [1-5]: 4, Tests, Review effort 4/5

#239 feat: Enhance AppSidebar with new icons and upload functionality
  backend/app/core/config.py
  backend/app/services/ai/deep_research_service.py
  backend/app/services/deep_research_service.py
  frontend/components/layout/AddContentModal.tsx
  frontend/components/layout/AppSidebar.tsx
  frontend/components/layout/EnhancedAddContentDialog.tsx
  frontend/components/layout/OptimizedAddContentDialog.tsx
  frontend/lib/utils.ts
  litellm/config.yaml
Labels: enhancement, Tests, Review effort 4/5, Possible security concern

#242 UI/0628
  backend/app/api/routes/content.py
  backend/app/core/config.py
  backend/app/prompt_templates/summary.j2
  backend/app/services/preprocessing_pipeline.py
  backend/scripts/debug_ai_processing.py
  backend/scripts/monitor_ai_processing.py
  frontend/__tests__/components/layout/AddContentModal.test.tsx
  frontend/__tests__/hooks/useRelativeTime.test.ts
  frontend/app/content-library/components/ContentCard.tsx
  frontend/app/content-library/components/ContentPreview.tsx
  frontend/app/content-library/components/Toolbar.tsx
  frontend/app/content-library/hooks/useContentItems.ts
  frontend/app/globals.css
  frontend/components/layout/AddContentModal.tsx
  frontend/components/providers/NotificationProvider.tsx
  frontend/components/ui/ProcessingStatusBadge.tsx
  frontend/hooks/useRelativeTime.ts
  frontend/package.json
  frontend/pnpm-lock.yaml
  litellm/config.yaml
Labels: enhancement, Review effort 4/5
