Repository telepace/nexus, pull requests merged in 2025-05, with the labels that each got.

#43 chore: update docker-build workflow to remove main branch trigger
  .github/workflows/docker-build.yml
  .github/workflows/generate-client.yml
  Makefile
  backend/app/core/config.py
  backend/app/tests_pre_start.py
  frontend/next.config.js
Labels: enhancement, Review effort [1-5]: 1

#62 Fix(admin): Update Playwright auth setup URL expectation
  Makefile
  admin/package.json
  admin/pnpm-lock.yaml
  admin/tests/auth.setup.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#63 feat: 添加动漫头像功能到用户资料页面
  frontend/__tests__/components/ProfileForm.debug.test.tsx
  frontend/__tests__/components/ProfileForm.simple.test.tsx
  frontend/__tests__/components/ProfileForm.test.tsx
  frontend/app/customers/components/ProfileForm.tsx
  frontend/lib/client-auth.ts
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 4, frontend, Tests, ui, Review effort 3/5

#68 Fix: Resolve test failures in ExtensionLauncherTest and SettingsPanel…
  frontend/__tests__/components/layout/SettingsPanel.test.tsx
  frontend/__tests__/components/setup/ExtensionLauncherTest.tsx
  frontend/jest.setup.js
  frontend/package-lock.json
Labels: Tests, Review effort [1-5]: 3

#66 feat: Add Playwright e2e tests for frontend
  Makefile
  frontend/app/page.tsx
  frontend/package.json
  frontend/playwright-report/data/e088f9484cac90cfcaf6ac00e3b4c23169296bbc.md
  frontend/playwright-report/index.html
  frontend/playwright.config.ts
  frontend/pnpm-lock.yaml
  frontend/tests/e2e/smoke.spec.ts
Labels: enhancement, Review effort [1-5]: 4, Tests

#70 feat: 更新 Tailwind CSS 配置和全局样式
  frontend/app/globals.css
  frontend/tailwind.config.js
Labels: enhancement, Review effort [1-5]: 4, Review effort 2/5

#74 Add new UI components (Alert, Toast)
  frontend/app/globals.css
  frontend/components/ui/alert-dialog.tsx
  frontend/components/ui/alert.tsx
  frontend/components/ui/avatar.tsx
  frontend/components/ui/badge.tsx
  frontend/components/ui/breadcrumb.tsx
  frontend/components/ui/button.tsx
  frontend/components/ui/card.tsx
  frontend/components/ui/command.tsx
  frontend/components/ui/dialog.tsx
  frontend/components/ui/dropdown-menu.tsx
  frontend/components/ui/form.tsx
  frontend/components/ui/input.tsx
  frontend/components/ui/label.tsx
  frontend/components/ui/menubar.tsx
  frontend/components/ui/navigation-menu.tsx
  frontend/components/ui/popover.tsx
  frontend/components/ui/progress.tsx
  frontend/components/ui/radio-group.tsx
  frontend/components/ui/scroll-area.tsx
  frontend/components/ui/select.tsx
  frontend/components/ui/separator.tsx
  frontend/components/ui/sheet.tsx
  frontend/components/ui/sidebar.tsx
  frontend/components/ui/skeleton.tsx
  frontend/components/ui/sonner.tsx
  frontend/components/ui/switch.tsx
  frontend/components/ui/table.tsx
  frontend/components/ui/tabs.tsx
  frontend/components/ui/textarea.tsx
  frontend/components/ui/toast.tsx
  frontend/components/ui/toaster.tsx
  frontend/components/ui/tooltip.tsx
  frontend/components/ui/use-toast.tsx
  frontend/hooks/use-mobile.tsx
  frontend/hooks/use-toast.ts
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/tailwind.config.js
Labels: enhancement, Other, Review effort 4/5

#80 新增 UI 设计系统指南文档，详细说明了组件开发、样式规则、可访问性和命名约定等最佳实践，以确保项目中的 UI 代码一致性和可维护性。
  .cursor/rules/ui.mdc
  backend/app/tests/conftest.py
Labels: enhancement, Review effort 1/5, Review effort [1-5]: 2

#78 Feature/frontend test
  .cursor/rules/ui.mdc
Labels: enhancement, Review effort 1/5, Review effort [1-5]: 2

#81 Feature/frontenttest
  backend/app/tests/conftest.py
  backend/pyproject.toml
  backend/test_db.py
  backend/uv.lock
  frontend/__tests__/app/dashboard/PromptNavigation.test.tsx
  frontend/__tests__/components/ProfileForm.test.tsx
  frontend/__tests__/components/layout/AddContentModal.test.tsx
  frontend/__tests__/components/layout/SettingsPanel.test.tsx
  frontend/__tests__/components/layout/Sidebar.test.tsx
  frontend/__tests__/components/layout/TopNavigation.test.tsx
  frontend/__tests__/customers.test.tsx
  frontend/__tests__/passwordResetConfirm.test.tsx
  frontend/__tests__/passwordResetConfirmPage.test.tsx
  frontend/__tests__/registerPage.test.tsx
  frontend/components/layout/AddContentModal.tsx
  frontend/jest.config.ts
  frontend/openapi.json
Labels: enhancement, Review effort [1-5]: 4, Tests, Bug fix, Review effort 3/5

#84 chore: enhance user profile management with avatar upload feature
  .cursor/rules/frontend.mdc
  .env.example
  .github/workflows/test-backend.yml
  .github/workflows/use-make-test.yml
  .github/workflows/website-ci.yml
  Makefile
  admin/README.md
  admin/src/client/sdk.gen.ts
  admin/src/client/types.gen.ts
  backend/.gitignore
  backend/app/alembic/versions/dd4b00c23094_add_avatar_url_to_user.py
  backend/app/api/routes/users.py
  backend/app/base.py
  backend/app/core/config.py
  backend/app/crud.py
  backend/app/main.py
  backend/app/tests/api/routes/test_users.py
  backend/app/tests/api/test_users.py
  backend/app/tests/conftest.py
  backend/app/tests/utils/test_db.py
  backend/app/tests/utils/test_image_utils.py
  backend/app/tests/utils/test_image_utils_with_storage.py
  backend/app/tests/utils/test_storage.py
  backend/app/utils/image_utils.py
  backend/app/utils/storage/__init__.py
  backend/app/utils/storage/base.py
  backend/app/utils/storage/local.py
  backend/app/utils/storage/r2.py
  backend/app/utils/storage/s3.py
  backend/package-lock.json
  backend/pyproject.toml
  backend/requirements.txt
  backend/scripts/migrate_storage.py
  backend/test_db.py
  backend/uv.lock
  development.md
  extension/README.md
  frontend/__tests__/components/layout/SettingsPanel.test.tsx
  frontend/__tests__/passwordResetConfirmPage.test.tsx
  frontend/__tests__/register.test.ts
  frontend/__tests__/registerPage.test.tsx
  frontend/app/openapi-client/sdk.gen.ts
  frontend/app/openapi-client/types.gen.ts
  frontend/app/password-recovery/confirm/page.tsx
  frontend/components/layout/SettingsPanel.tsx
  frontend/components/layout/TopNavigation.tsx
  frontend/lib/definitions.ts
  frontend/openapi.json
  frontend/playwright.config.ts
  frontend/pnpm-lock.yaml
  frontend/tests/auth.setup.ts
  frontend/tests/e2e/smoke.spec.ts
  website/src/content/zh/docs/frontend/index.mdx
Labels: enhancement, Review effort [1-5]: 4, Tests, Bug fix

#98 feat: Increase backend test coverage
  backend/app/tests/api/middlewares/test_posthog.py
  backend/app/tests/api/middlewares/test_response.py
  backend/app/tests/api/routes/test_extension_auth.py
  backend/app/tests/api/routes/test_google_oauth.py
  backend/app/tests/api/routes/test_prompts.py
  backend/app/tests/crud/test_generic_crud.py
  backend/app/tests/crud/test_item_crud.py
  backend/app/tests/crud/test_tag_crud.py
  backend/app/tests/crud/test_token_blacklist_crud.py
  backend/app/tests/crud/test_user.py
  backend/app/tests/utils/storage/test_s3.py
Labels: Review effort [1-5]: 4, Tests

#105 Jules was unable to complete the task in time.
  .github/workflows/test-backend.yml
  Makefile
  README.md
  README_zh-CN.md
  admin/src/client/sdk.gen.ts
  admin/src/client/types.gen.ts
  backend/.gitignore
  backend/app/alembic/env.py
  backend/app/api/routes/prompts.py
  backend/app/api/routes/users.py
  backend/app/base.py
  backend/app/core/config.py
  backend/app/core/db.py
  backend/app/crud.py
  backend/app/main.py
  backend/app/tests/api/middlewares/test_posthog.py
  backend/app/tests/api/middlewares/test_response.py
  backend/app/tests/api/routes/test_extension_auth.py
  backend/app/tests/api/routes/test_google_oauth.py
  backend/app/tests/api/routes/test_login.py
  backend/app/tests/api/routes/test_prompts.py
  backend/app/tests/api/routes/test_users.py
  backend/app/tests/api/test_users.py
  backend/app/tests/conftest.py
  backend/app/tests/crud/test_generic_crud.py
  backend/app/tests/crud/test_item_crud.py
  backend/app/tests/crud/test_tag_crud.py
  backend/app/tests/crud/test_token_blacklist_crud.py
  backend/app/tests/crud/test_user.py
  backend/app/tests/utils/storage/test_s3.py
  backend/app/tests/utils/test_db.py
  backend/app/tests_pre_start.py
  backend/package-lock.json
  backend/pyproject.toml
  backend/pytest.ini
  backend/scripts/test-debug.py
  backend/scripts/test-init-data.py
  backend/scripts/test.sh
  backend/scripts/tests-start.sh
  backend/test_db.py
  backend/uv.lock
  copier.yml
  deployment.md
  deployment_zh-CN.md
  docker-compose.override.yml
  docs/cicd/environment-secrets.md
  docs/guides/fly-deployment.md
  frontend/app/openapi-client/sdk.gen.ts
  frontend/app/openapi-client/types.gen.ts
  frontend/openapi.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  helm-charts/nexus/values.local.yaml
  helm-charts/nexus/values.prod.yaml
  helm-charts/nexus/values.yaml
  package.json
  pnpm-lock.yaml
  scripts/check-uv.sh
  website/src/components/ui/card.tsx
  website/tailwind.config.ts
Labels: enhancement, Review effort [1-5]: 4, Tests

#93 This message describes code changes and does not violate any of the r…
  .env.example
  .github/workflows/playwright.yml
  .github/workflows/test-backend.yml
  admin/playwright.config.ts
  backend/app/api/main.py
  backend/app/api/routes/llm_service.py
  backend/app/core/config.py
  backend/app/schemas/llm.py
  backend/app/tests/api/routes/test_llm_service.py
  backend/scripts/test.sh
  backend/scripts/tests-start.sh
  docker-compose.override.yml
  frontend/playwright.config.ts
Labels: enhancement, Review effort [1-5]: 4, Tests

#107 Fix: Resolve frontend test failures
  frontend/__tests__/app/setup/SetupPageTest.tsx
  frontend/__tests__/login.test.tsx
  frontend/__tests__/registerPage.test.tsx
  frontend/jest.setup.js
  frontend/pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 4, Tests

#110 Fix: Resolve ESLint errors and warnings in website directory
  website/content/en/_meta.js
  website/content/en/blog/_meta.js
  website/content/zh/_meta.js
  website/content/zh/blog/_meta.js
  website/fly.toml
  website/mdx-components.tsx
  website/next.config.ts
  website/src/app/[lang]/[[...mdxPath]]/page.tsx
  website/src/app/[lang]/_app.tsx
  website/src/app/[lang]/_components/CustomBanner.tsx
  website/src/app/[lang]/_components/CustomNavbar.tsx
  website/src/app/[lang]/_components/LastUpdatedWrapper.tsx
  website/src/app/[lang]/_components/NextraStyleFix.tsx
  website/src/app/[lang]/blog/_meta.zh.js
  website/src/app/[lang]/layout.tsx
  website/src/app/_dictionaries/dictionaries.ts
  website/src/app/layout.tsx
  website/src/app/not-found.tsx
  website/src/app/page.tsx
  website/src/components/BlogButton/index.tsx
  website/src/components/ClientMDXWrapper.jsx
  website/src/components/ClientMDXWrapper.tsx
  website/src/components/HomepageHero/HomepageHero.tsx
  website/src/components/HomepageHero/Setup.tsx
  website/src/components/HomepageHero/index.tsx
  website/src/components/NextraLink.tsx
  website/src/components/PanelParticles/PanelParticles.tsx
  website/src/components/PanelParticles/index.ts
  website/src/components/ui/card.tsx
  website/src/components/ui/flip-words.tsx
  website/src/components/ui/link-preview.tsx
  website/src/hooks/useServerLocale.ts
  website/src/i18n/en.ts
  website/src/i18n/index.ts
  website/src/i18n/zh.ts
  website/tailwind.config.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#120 chore: update GitHub issue operation guidelines
  .cursor/rules/github-issue-operation.mdc
  .github/workflows/test-backend.yml
  backend/scripts/test.sh
  backend/scripts/tests-start.sh
Labels: documentation, enhancement, Review effort [1-5]: 4

#91 feat: Unify and optimize frontend login/redirect logic
  admin/src/client/sdk.gen.ts
  admin/src/client/types.gen.ts
  backend/app/alembic/versions/568a9c9e88d4_add_is_setup_complete_to_user.py
  backend/app/base.py
  frontend/app/login/page.tsx
  frontend/app/openapi-client/sdk.gen.ts
  frontend/app/openapi-client/types.gen.ts
  frontend/app/page.tsx
  frontend/app/register/page.tsx
  frontend/app/setup/page.tsx
  frontend/components/setup/SetupContent.tsx
  frontend/hooks/useAuthRedirect.ts
  frontend/lib/client-auth.ts
  frontend/lib/server-auth.ts
  frontend/middleware.ts
  frontend/openapi.json
Labels: enhancement, Review effort [1-5]: 4

#118 fix(website): Address build issues and Nextra setup
  website/mdx-components.tsx
  website/next.config.ts
  website/src/components/ui/link-preview.tsx
  website/theme.config.tsx
  website/tsconfig.json
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#92 feat: Enhance frontend UI components and API error handling
  frontend/app/prompts/_components/PromptForm.tsx
  frontend/app/prompts/create/page.tsx
  frontend/app/prompts/edit/[id]/page.tsx
  frontend/components/actions/prompts-action.ts
  frontend/components/ui/button.tsx
  frontend/components/ui/card.tsx
  frontend/components/ui/input.tsx
Labels: enhancement, Review effort [1-5]: 4

#130 更新前端实现指南和全局样式，增强了文档结构和可读性。调整了CSS自定义属性的定义，优化了颜色和间距的语义化映射，确保与Tailwind C…
  .cursor/rules/ui.mdc
  frontend/app/globals.css
Labels: documentation, enhancement, Review effort [1-5]: 4, Review effort 2/5
